### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by marcialwushu** [marcialwushu/Ionic3Firebase-Estudo#1]
Runtime Error 
Object(...) is not a function

```
TypeError: Object(...) is not a function
    at SwitchMapSubscriber.project (http://localhost:8100/build/vendor.js:84902:76)
    at SwitchMapSubscriber._next (http://localhost:8100/build/vendor.js:58122:27)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:20750:18)
    at RefCountSubscriber.Subscriber._next (http://localhost:8100/build/vendor.js:20786:26)
    at RefCountSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:20750:18)
    at Subject.next (http://localhost:8100/build/vendor.js:23237:25)
    at ConnectableSubscriber.Subscriber._next (http://localhost:8100/build/vendor.js:20786:26)
    at ConnectableSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:20750:18)
    at Notification.observe (http://localhost:8100/build/vendor.js:50358:50)
    at AsyncAction.DelaySubscriber.dispatch (http://localhost:8100/build/vendor.js:69159:40)

```

I'm developing my first aplication with Ionic, and would like to display the firebase data at home.html, but when I start the serve show me this message in browser:

```
object(...) is not a function
```

**Comment by marcialwushu** [comment]
Are you sure that c.payload.val is a function and not an Object (holding data or maybe even holding a function)

**Comment by marcialwushu** [comment]
https://stackoverflow.com/questions/50478804/runtime-error-object-is-not-a-function
